(set colours '(blue yellow green red))

(set initial-state '((sea . blue) (iceland) (cyprus) (england) (ireland)
                      (sweden) (norway) (finland) (italy) (vatykan) (sant-marino)
                      (austria) (swiss) (france) (monaco) (spain) (portugal)
                      (giblartar) (andora) (linchestein) (turkey) (russia) (bulgaria)
                      (makedonia) (serbia) (romania) (hungary) (kroatia)
                      (slovenia) (greece) (belarus) (czech) (bosnia) (albania)
                      (ukraine) (belgium) (luxembourg) (netherlands) (germany) (denmark)
                      (poland) (moldova) (slovakia) (lithuania)
                      (latvia) (estonia)))
                      
(set map '(
    (sea cyprus turkey greece bulgaria romania ukraine russia albania
     serbia bosnia kroatia slovenia italy monaco france spain giblartar
     portugal england ireland belgium netherlands iceland germany
     denmark poland lithuania latvia estonia finland sweden norway)
    (cyprus sea)
    (iceland sea)
    (england sea ireland)
    (ireland sea england)
    (sweden sea norway finland)
    (norway sea sweden finland russia)
    (finland sea sweden norway russia)
    (denmark sea germany)
    (germany sea denmark poland czech austria swiss france luxembourg belgium netherlands)
    (spain sea giblartar portugal andora france)
    (portugal sea spain)
    (giblartar sea spain)
    (andora spain france)
    (monaco sea france)
    (france sea spain andora belgium luxembourg germany swiss italy monaco)
    (italy sea france swiss austria slovenia vatykan sant-marino)
    (vatykan italy)
    (sant-marino italy )
    (albania sea greece makedonia serbia)
    (serbia sea albania makedonia bulgaria romania hungary kroatia bosnia)
    (romania sea bulgaria serbia hungary ukraine moldova)
    (turkey sea bulgaria greece)
    (greece sea turkey bulgaria makedonia albania)
    (bulgaria sea greece turkey makedonia serbia romania)
    (bosnia sea kroatia serbia)
    (kroatia sea slovenia hungary serbia bosnia)
    (slovenia sea italy austria hungary kroatia)
    (belgium sea netherlands germany luxembourg france)
    (netherlands sea germany belgium)
    (poland sea russia lithuania belarus ukraine slovakia czech germany)
    (ukraine sea romania moldova hungary slovakia poland belarus russia)
    (russia sea ukraine belarus poland lithuania latvia estonia finland norway)
    (lithuania sea latvia belarus poland russia)
    (latvia sea estonia russia belarus lithuania)
    (estonia sea russia latvia)
    (makedonia greece albania bulgaria serbia)
    (hungary serbia kroatia slovenia austria slovakia ukraine romania)
    (slovakia hungary austria czech poland ukraine)
    (austria slovenia italy linchestein swiss germany czech slovakia hungary )
    (linchestein swiss austria)
    (swiss france germany austria linchestein italy)
    (luxembourg france belgium germany)
    (czech austria germany poland slovakia)
    (moldova romania ukraine)
    (belarus ukraine poland lithuania latvia russia)))
