rock5b = {
    color = (1 1 1 1)
    texture = "data/materials/rock/stone5_b.tga"
}

rock5c = {
    color = (1 1 1 1)
    texture = "data/materials/rock/stone5_c.tga"
}

rough_rock1a = {
    color = (1 1 1 1)
    texture = "data/materials/rrock1/kt_rock_1.tga"
}

rough_rock1b = {
    color = (1 1 1 1)
    texture = "data/materials/rrock1/kt_rock_1b.tga"
}

rough_rock1c = {
    color = (1 1 1 1)
    texture = "data/materials/rrock1/kt_rock_1c.tga"
}

rough_rock1d = {
    color = (1 1 1 1)
    texture = "data/materials/rrock1/kt_rock_1g.tga"
}

rough_rock2 = {
    color = (1 1 1 1)
    texture = "data/materials/rrock1/kt_rock_2.tga"
}

rough_rock3 = {
    color = (1 1 1 1)
    texture = "data/materials/rrock1/kt_rock_3_grn.tga"
}

rough_rock4 = {
    color = (1 1 1 1)
    texture = "data/materials/rrock1/kt_rock_4_grn.tga"
}
