(defun create-character (name)
    (make-instance C/CHARACTER name))

(defun set-attributes (c str dex end int per)
    (set-str c str)
    (set-dex c dex)
    (set-end c end)
    (set-int c int)
    (set-per c per)
    c)

(defun get-attributes (c)
    (list (get-str c) (get-dex c) (get-end c) (get-int c) (get-per c)))


(setq c (create-character "John Dee"))
(set-model c (get-model *dataset* "blade"))
(set-attributes c 15 10 10 12 17) 
(add *party* c)


(setq c (create-character "John Doo"))
(set-model c (get-model *dataset* "blade"))
(set-attributes c 15 10 10 12 17) 
(add *party* c)

