(load-dataset *level* "data/test/micro_dataset.dl")

(init *level* 10 10)
(finalize *level*)

(defun place-tile (x y name)
    (place-tile-by-name *level* x y name))

(defun place-wall-x (x y d name)
    (dotimes (dx d)
        (place-tile (+ x dx) y name)))

(defun place-wall-y (x y d name)
    (dotimes (dy d)
        (place-tile x (+ y dy) name)))

;; (create-object C/OBJECT)

(place-object-by-name *level* 5 5 "blade")

(defun create-character (name)
    (make-instance C/CHARACTER name))

(defun init-character (c model )
    (progn 
        (set-model c (get-model *dataset* model))
        c))

(place-object *level* 1 1 
    (init-character (create-character "John Dee") "blade"))


(place-tile 0 0 "wall")


(place-wall-x 0 0 10 "wall")
(place-wall-x 0 9 10 "wall")
(place-wall-y 0 0 10 "wall")
(place-wall-y 9 0 10 "wall")

