(load-dataset *level* "data/test/micro_dataset.dl")

(init *level* 10 10)
(finalize *level*)

(defun place-tile (x y name)
    (place-tile-by-name *level* x y name))

(defun place-wall-x (x y d name)
    (dotimes (dx d)
        (place-tile (+ x dx) y name)))

(defun place-wall-y (x y d name)
    (dotimes (dy d)
        (place-tile x (+ y dy) name)))

;; (create-object C/OBJECT)

(place-object-by-name *level* 5 5 "blade")

(defun place-john ()
    (let ((john (make-instance C/CHARACTER "John Dee")))
        (print (get-attr (get-attr john 'parent) 'parent))
        (set-model john (get-model *dataset* "blade"))
        (place-object *level* 2 2 john)))
(place-john)

(place-tile 0 0 "wall")


(place-wall-x 0 0 10 "wall")
(place-wall-x 0 9 10 "wall")
(place-wall-y 0 0 10 "wall")
(place-wall-y 9 0 10 "wall")

